# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clinicUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('smokingHistory', models.BooleanField(default=False)),
                ('allergies', models.CharField(max_length=50)),
                ('cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('hemoptysis', models.BooleanField(default=False)),
                ('breathlessness', models.BooleanField(default=False)),
                ('skinrash', models.BooleanField(default=False)),
                ('tb', models.BooleanField(default=False)),
                ('cvd', models.BooleanField(default=False)),
                ('sinusitis', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('dm', models.BooleanField(default=False)),
                ('hiv', models.BooleanField(default=False)),
            ],
        ),
    ]
