# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170516_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicuserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='clinicuserprofile',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
