# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_radiouserprofilechest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuserprofile',
            name='mining',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinicuserprofile',
            name='allergies',
            field=models.CharField(blank=True, default='NIL', max_length=50),
        ),
    ]
