# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_clinicuserprofile_eosinophilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuserprofile',
            name='age',
            field=models.CharField(default='25', max_length=3),
        ),
        migrations.AddField(
            model_name='clinicuserprofile',
            name='sex',
            field=models.CharField(default='MALE', max_length=10),
        ),
    ]
