# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170608_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='bronchiectasis',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='cavity',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='cysts',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='fibrosis',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='groundGlass',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='heart',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='lymphNodes',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='nodules',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='pleuralThickening',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.AlterField(
            model_name='radiouserprofilechest',
            name='septal',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
